import os
import platform
import secrets
import psutil
from pathlib import Path
import typer
from rich.prompt import Prompt, Confirm
from ..ui import console, print_banner, print_success, print_error, print_warning, print_info, print_step
from ..config import save_config, DEFAULT_CONFIG
from ..services.docker_service import (
    is_docker_installed,
    is_docker_running,
    get_docker_version,
    install_docker_hint,
    get_workspace_root
)

def run_init():
    print_banner("Interactive Setup Wizard")
    console.print("[bold]Welcome to StackPilot![/bold] Let's configure your local environment in 60 seconds.\n")

    # 1. System Audit
    mem = psutil.virtual_memory().total / (1024 ** 3)
    cpu_cores = psutil.cpu_count(logical=True)
    os_name = platform.system()
    print_step("🖥️", "System Audit", f"{os_name} | {cpu_cores} Cores | {mem:.1f} GB RAM")

    potato_mode = False
    if mem < 8.0:
        print_warning(f"Detected {mem:.1f} GB RAM (< 8 GB). Enabling Potato / Eco Mode is recommended.")
        potato_mode = Confirm.ask("Enable Potato / Eco Mode for low resource usage?", default=True)

    # 2. Docker Audit
    print_step("🐳", "Checking Docker Engine...")
    docker_ok = is_docker_installed()
    docker_running = is_docker_running()

    if not docker_ok:
        print_warning("Docker is not installed on your system.")
        console.print(f"Hint: [cyan]{install_docker_hint()}[/cyan]\n")
        install_now = Confirm.ask("Would you like to install Docker automatically now?", default=True)
        if install_now:
            if os_name.lower() == "windows":
                console.print("[dim]Executing: winget install -e --id Docker.DockerDesktop[/dim]")
                os.system("winget install -e --id Docker.DockerDesktop --accept-source-agreements --accept-package-agreements")
            elif os_name.lower() == "darwin":
                console.print("[dim]Executing: brew install --cask docker[/dim]")
                os.system("brew install --cask docker")
            else:
                console.print("[dim]Executing Docker install script...[/dim]")
                os.system("curl -fsSL https://get.docker.com | sh")
    elif not docker_running:
        print_warning("Docker is installed but the Docker daemon is NOT running.")
        print_info("Please start Docker Desktop or the dockerd service.")
    else:
        v = get_docker_version() or "detected"
        print_success(f"Docker is running ({v})")

    # 3. Profile selection
    console.print("\n[bold magenta]Modular Feature Profile Selection:[/bold magenta]")
    console.print("  [1] [bold cyan]Core QA & Testing[/bold cyan] (AI Service, Browser Sandbox, 60fps Stream, Frontend) [~1.5 GB RAM]")
    console.print("  [2] [bold green]Full Platform[/bold green] (Core + C++ Backend + Git Webhooks + Build Engine) [~1.8 GB RAM]")
    console.print("  [3] [bold yellow]Enterprise Suite[/bold yellow] (Full + Prometheus, Grafana, Loki Monitoring) [~2.6 GB RAM]")

    profile_choice = Prompt.ask("Choose profile", choices=["1", "2", "3"], default="1")
    profile_map = {"1": "core", "2": "full", "3": "monitoring"}
    selected_profile = profile_map[profile_choice]

    # 4. AI Provider & Keys
    console.print("\n[bold magenta]AI Intelligence Configuration:[/bold magenta]")
    console.print("  [1] OpenAI (GPT-4o / GPT-4o-mini)")
    console.print("  [2] Anthropic Claude (Claude 3.5 Sonnet)")
    console.print("  [3] Google Gemini (Gemini 2.5 Flash / Pro)")
    console.print("  [4] NVIDIA NIM / OpenAI Compatible / Local Ollama")

    ai_choice = Prompt.ask("Select AI provider", choices=["1", "2", "3", "4"], default="1")
    provider_names = {"1": "openai", "2": "anthropic", "3": "gemini", "4": "openai_compatible"}
    selected_provider = provider_names[ai_choice]

    api_key = Prompt.ask("Enter AI API Key (input will be masked)", password=True, default="")

    # 5. Generate secure secrets
    jwt_secret = secrets.token_hex(32)
    db_password = secrets.token_hex(16)
    service_token = secrets.token_hex(32)

    # 6. Save CLI configuration
    cfg = DEFAULT_CONFIG.copy()
    cfg["default_profile"] = selected_profile
    cfg["potato_mode"] = potato_mode
    save_config(cfg)

    # 7. Write workspace .env if in workspace
    root = get_workspace_root()
    env_path = root / ".env"
    if not env_path.exists():
        env_content = f"""# StackPilot Environment Configuration (Generated by CLI)
DB_USER=stackpilot
DB_PASSWORD={db_password}
DB_NAME=stackpilot
JWT_SECRET={jwt_secret}
STACKPILOT_AI_SERVICE_TOKEN={service_token}

# AI Settings
STACKPILOT_AI_PROVIDER={selected_provider}
OPENAI_API_KEY={api_key if selected_provider == 'openai' else ''}
ANTHROPIC_API_KEY={api_key if selected_provider == 'anthropic' else ''}
GEMINI_API_KEY={api_key if selected_provider == 'gemini' else ''}

# Ports
BACKEND_PORT=8090
AI_SERVICE_PORT=8010
FRONTEND_PORT=3000
"""
        try:
            with open(env_path, "w", encoding="utf-8") as f:
                f.write(env_content)
            print_success(f"Generated environment file: {env_path}")
        except Exception as e:
            print_warning(f"Could not write .env directly: {e}")

    print_success("Setup complete!")
    console.print("\n[bold]Next Steps:[/bold]")
    console.print("  • Run [bold cyan]stackpilot doctor[/bold cyan] to verify system health.")
    console.print("  • Run [bold cyan]stackpilot up[/bold cyan] to start StackPilot services.")
    console.print("  • Run [bold cyan]stackpilot test <url>[/bold cyan] to test a website autonomously.")
    console.print("  • Run [bold cyan]stackpilot chat[/bold cyan] to chat with the AI co-pilot.\n")
